### PR TITLE
WIP: Clarify icon meaning (#304)

### LINKED ISSUE #304: Clarify meaning or change iconography for red "remove plate" Xs in interface
User asked,  "Why there are there red x's there?", worried there was an error 
Raised in shotgun walkthrough 07/31/2018

### PR DESCRIPTION
**Pull request by wasade**
Before working through the rest of th to resolve #304, does this type modification work? It adds a human readable message about the status in addition to color and icon. For some pages, the strategy may need to differ. 

improve-icon-clarity

### CODE REVIEW

**Comment by charles-cowart** [comment]
Slick! :)

**Comment by wasade** [comment]
This was merged prematurely, note that it is still a WIP as there are other pages where this clarification is necessary. I've reopened #304 to reflect this.

**Comment by charles-cowart** [comment]
Thanks! I didn't notice the WIP.

**Comment by AmandaBirmingham** [comment]
@wasade This functionality is entirely awesome!  I will be thrilled to see it in the software! 

I therefore hesitate to point out that the (legit) problem it is fixing is not the one I was trying to capture in the issue #304 write-up :)  The issue I was recording there was actually much simpler ... a user thought the "x" in a red circle that appears next to a plate in a list of selected plates (in compression page, extraction page, library prep pages, etc--see screenshot below from compression page as an example) was an error message indicating they had done something wrong, whereas in fact it is just a "remove" button to show that you can remove the plate from the selected list  :( .    Possibly all that misunderstanding requires is a tool tip or something.

Screen Shot 2019-04-18 at 10 38 13 PM

I'll add this additional info to #304 to augment its clearly inadequate description :)

**Comment by wasade** [comment]
Thanks! I was working toward that to be honest :) My initial attempt was to explore different glyphicons that were friendlier but didn't see any. I then tried to figure out if and how to place text immediately next to the button to provide clarity but was unable to make that work (possibly or likely due to limited HTML/JS experience). A tooltip is certainly a great idea, and seems like it may be a relatively "easy" thing to add in!

**Comment by AmandaBirmingham** [comment]
@wasade I had another thought: in addition to a tooltip, maybe another help would be simply to *change the color* of the little X circle icon for removing the plates.  Interface convention has trained users that *red* usually means "error" ... maybe the X icon could be black or gray?  You know, the way it is in most interfaces where it offers low-danger functionality like "shut this box" ...

**Comment by wasade** [comment]
:+1:

**Pull request merged**
