### PR TITLE
Solving plating issues

### LINKED ISSUE #27: when viewing already plated plate, you should have studies on the plate listed on page
when viewing any plate, the study or studies should be listed on the page so that you know what you are looking at.  currently it still displays option for "Studies being plated +add study"

### LINKED ISSUE #34: Blank Labeling Structure
When blanks are auto-populated they need to be labeled as following "BlankPlate#.ColumnRow"

### LINKED ISSUE #43: Making comments
need to be able to easily make notes about a specific sample and highlight samples that are from certain studies

### PR DESCRIPTION
**Pull request by josenavas**
Fixes #34 
Fixes #27
Fixes #43

It also fixes the issue in which the sample lookup was returning so many result that was crashing the interface. Now it is limited to 20.

### CODE REVIEW

**Comment by jdereus** [comment]
please address failed tests

**Comment by jdereus** [comment]
can you resolve conflicts first?

**Comment by josenavas** [comment]
I totally forgot that I also did DB changes in this one when I started working on the other PR, luckily the changes here in the DB where easy enough that it wasn't a complete mess. Let's wait until the tests pass and then get it merge, so I can actually do the changes for Amplicon Library Prep without incurring in more merge conflicts. Thanks @jdereus !

**Comment by josenavas** [comment]
Yay!! Tests passed - can I get this merged?

**Pull request merged**
