### PR TITLE
Partial name change to Labcontrol

### PR DESCRIPTION
**Pull request by charles-cowart**
'labman' source directory renamed to 'labcontrol'. All from and import references to 'labman.something' changed to 'labcontrol.something'. There are other references to labman that are yet to be changed to labcontrol; this should be just the minimum amount required to rename the labman source directory.

### CODE REVIEW

**Comment by charles-cowart** [comment]
Just to reiterate, this doesn't include name changes in the database schema, etc. This was the minimum required to rename the source directory from 'labman' to 'labcontrol'.

**Comment by AmandaBirmingham** [comment]
Relevant to #394

**Comment by charles-cowart** [comment]
Thanks everyone! Who would like to merge?

**Comment by AmandaBirmingham** [comment]
@charles-cowart  Go for it!

**Comment by charles-cowart** [comment]
ty!

**Pull request merged**
