### PR TITLE
modified sequence process interface

### PR DESCRIPTION
**Pull request by qiyunzhu**
The "sequence process" interface was partially modified.

- Added lane number function.
- Added select pool modal.
- Added functionalities to get the above two work with each other.
- I cannot figure out how to let modal retrieve pool information from the database, so I leave the multi select element in the page. It should be removed though.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
Hi @josenavas I have modified the "additional contacts" input interface, and now would like to have your advice before moving on.

screen shot 2018-01-19 at 2 37 47 pm

 - Could you please take a look at this section and let me know whether the code reasonable. (Note: the "sequencing pools" functionality is not complete yet.)
 - I am not sure how to post an array to the backend?
 - It looks to me that the backend handler, `SequencingProcess.create()`, cannot handle multiple pool IDs, and I am confused by how it handles additional contacts.
 - Must principal investigator be excluded from additional contacts? Must principal investigator be chosen before one can select additional contacts?

Thank you!

**Comment by josenavas** [comment]
Hi @qiyunzhu 

To send an array to the backend you will need to do: `JSON.stringify(array)`

you're right about the SequencingProcess.create call - I will do another PR fixing that - in the meantime assume this API (which is the one that I'm going to change to):

```python
    def create(cls, user, pools, run_name, experiment, sequencer,
               fwd_cycles, rev_cycles, assay, principal_investigator,
               contacts=None):
        """Creates a new sequencing process

        Parameters
        ----------
        user : labman.db.user.User
            User preparing the sequencing
        pools: list of labman.db.composition.PoolComposition
            The pools being sequenced
        run_name: str
            The run name
        experiment: str
            The run experiment
        sequencer: labman.db.equipment.Equipment
            The sequencer used
        fwd_cycles : int
            The number of forward cycles
        rev_cycles : int
            The number of reverse cycles
        assay : str
            The assay used
        principal_investigator : labman.db.user.User
            The principal investigator to list in the run
        contacts: list of labman.db.user.User
             Any extra contacts
        Returns
        -------
        SequencingProcess

        Raises
        ------
        ValueError
            If the number of cycles are <= 0
        """
```

For the contacts you just need to pass a list of labman.db.user.User. To instantiate a user simply do: User(email)

No worries on excluding principal investigator from the list of contacts.

Given the needed change on the backed your tests will fail but at least the interface will be completed.

Thanks!

**Comment by josenavas** [comment]
Hi @qiyunzhu 

I just chatted with @tanes - we are not going to ask for the "assay" element, we can infer it internally, so we avoid user errors. This is the new interface:

```python
    def create(cls, user, pools, run_name, experiment, sequencer,
               fwd_cycles, rev_cycles, principal_investigator, contacts=None):
        """Creates a new sequencing process

        Parameters
        ----------
        user : labman.db.user.User
            User preparing the sequencing
        pools: list of labman.db.composition.PoolComposition
            The pools being sequenced
        run_name: str
            The run name
        experiment: str
            The run experiment
        sequencer: labman.db.equipment.Equipment
            The sequencer used
        fwd_cycles : int
            The number of forward cycles
        rev_cycles : int
            The number of reverse cycles
        principal_investigator : labman.db.user.User
            The principal investigator to list in the run
        contacts: list of labman.db.user.User
             Any extra contacts
        Returns
        -------
        SequencingProcess

        Raises
        ------
        ValueError
            If the number of cycles are <= 0
        """
```

**Comment by qiyunzhu** [comment]
@josenavas Thanks! So I will delete the "assay" input from the UI.

**Comment by qiyunzhu** [comment]
Hi @josenavas in your new interface, the parameter `experiment` is not mentioned anywhere in the original interface. Is it to be added?

**Comment by josenavas** [comment]
Yes please - it is just a string

Thanks!

**Comment by qiyunzhu** [comment]
@josenavas The interface is completed. Also added unit-test for the handler.

**Comment by josenavas** [comment]
Thanks @qiyunzhu Will take a look later

**Comment by josenavas** [comment]
Closing in favor of #84 - it includes these commits and makes sure the tests pass.

**Pull request closed without merging**
