### PR TITLE
Create index.rst to add tutorial-will need updates

### PR DESCRIPTION
**Pull request by adswafford**

### CODE REVIEW

**Comment by josenavas** [comment]
Thanks @adswafford !

Do you want me to merge this or are the updates going to be coming in this PR?

**Comment by adswafford** [comment]
Can you merge this and then we'll issue new PRs for updates to it as they
come?

--
Austin D. Swafford, PhD
Director of Research, Center for Microbiome Innovation
Jacobs School of Engineering *| *UC San Diego
O: 858-246-2906

*Follow @CMIDigest*

<http://ow.ly/kiac30dUAnc>    <http://ow.ly/fXyB30dUAoS>
<http://ow.ly/dKO130dUAuB>

**Comment by jdereus** [comment]
shouldn't someone from the wetlab have major input into this content?

**Comment by adswafford** [comment]
Stephanie and Carolina prepared it together and Jon has also looked over it
and provided comments that will need to be addressed, but it is still
missing parts since the system wasn't functional. It will definitely need
more eyes and input, changes and updates (including screenshots), but it
was becoming challenging to troubleshoot and test it without a recorded, if
imperfect, description of the anticipated usage.

--
Austin D. Swafford, PhD
Director of Research, Center for Microbiome Innovation
Jacobs School of Engineering *| *UC San Diego
O: 858-246-2906

*Follow @CMIDigest*

<http://ow.ly/kiac30dUAnc>    <http://ow.ly/fXyB30dUAoS>
<http://ow.ly/dKO130dUAuB>

**Comment by josenavas** [comment]
I agree with @jdereus - however, I also think it is useful to have a starting document that we can work on and improve as we move forward. I will merge for now and as updates are coming we can always udpate.

**Pull request merged**
