### PR TITLE
Study summary page

### PR DESCRIPTION
**Pull request by qiyunzhu**
Hello @josenavas I need your help in resolving this. I was trying to create a "study.html" page to display study information, but I couldn't get the "view study" button to navigate to this page, after many unsuccessful trials. Perhaps it was some small issue I missed. Here I am posting a blank page with (what I think) necessary linkings. Can you please take a look and let me know what is missing? Thanks!

### CODE REVIEW

**Comment by josenavas** [comment]
Hi @qiyunzhu !

You need to create an endpoint and add it to the webserver. [Here](https://github.com/jdereus/labman/blob/master/labman/gui/webserver.py#L59) is where you can add the endpoint.

Hope this helps!

**Comment by qiyunzhu** [comment]
Hi @josenavas Thanks for instant reply! I tried to use the existing `(r"/study/(.*)/", StudyHandler),` endpoint in `webserver.py`. Does that one not work?

**Comment by josenavas** [comment]
Hi @qiyunzhu 

That handler is used to achieve some functionality in the sample plating page - please do not alter it's response as it will break functionality somewhere else.

You'll need to create a new endpoint, I recommend `"/study/([0-9]+)/sample_summary"`.

Then, modify [this](https://github.com/jdereus/labman/pull/95/files#diff-5b18a77bbbc4a28437b757ba0d91f63bR28) to be

```JavaScript
window.location.href = '/study/' + $(this).attr('data-lb-study-id' + '/sample_summary');
```

Then, in the new handler, define the `get` function as:
```python
@authenticated
def get(self, study_id):
    ....
```
Tornadao will make sure that the number in the regex `"/study/([0-9]+)/sample_summary"` will be passed as a parameter to your get function.

Hope this helps!

**Comment by qiyunzhu** [comment]
@josenavas Cool! Let me try your way. Thanks for the help!

**Comment by josenavas** [comment]
No problem! Thank you!

**Comment by qiyunzhu** [comment]
@josenavas I got the study pages working following your guideline. Now there is a minimum study summary page displaying only sequence title and total number of samples. Once the backend db function is done, more display items can be added.

**Comment by josenavas** [comment]
Thanks @qiyunzhu 
There is a merge conflict - can you address?

Also - ETA for the backend function retrieving the rest of the information?

**Comment by qiyunzhu** [comment]
@josenavas thanks for reminding. Let me resolve the conflict. Pinging @mortonjt who is working on the SQL command.

**Pull request merged**
