### PR TITLE
Fixes #98

### LINKED ISSUE #98: Library pooling isn't working
On current master (e11c183), the library pooling doesn't work for me. 

1. if I select `Amplicon library plates`, it does not let me add the example test plate---green button appears, but clicking does nothing. screenshot
2. if I select `Shotgun library plates`, it allows me to add the example plate and select a pooling function, but then throws an error. screenshot

### PR DESCRIPTION
**Pull request by josenavas**
I've added two more tests to cover the bug.

### CODE REVIEW

**Comment by josenavas** [comment]
@tanaes can you take a look at this PR?

**Comment by tanaes** [comment]
Ready to merge?

**Comment by josenavas** [comment]
Yup!

**Comment by tanaes** [comment]
haha psych I don't have merge permissions.

**Pull request merged**
