### PR TITLE
ENH: Prepend study identifiers to samples

### LINKED ISSUE #209: Project ID Prepending
From the image, you can see that for American gut, the sample comes up as red unless the “10317” study ID is present… which creates another issue because then the user cannot see what the barcode actually is, it just gets cut off. Also, this of course makes both copy and pasting as well as scanning in the barcodes less effective because I then need to go back and add the study ID to verify that the sample is ok. 

screen shot 2018-02-22 at 09 30 25

### PR DESCRIPTION
**Pull request by ElDeveloper**
This should only happen when:

A study is selected, the sample name is not one of the known blank
names, and the sample name does not already include the study
identifier.

Fixes #209

This animated gif shows how this works (note that the first study I select has study id 2, and then the second study I select has study id 1):

plate-samples-with-ids

### CODE REVIEW

**Comment by tanaes** [comment]
Would it be possible to update this so that blanks are associated with studies as well? This would potentially solve the problem of associating a project-shortname to blanks: https://github.com/jdereus/labman/issues/204

**Comment by ElDeveloper** [comment]
Sure thing, I'll have a look at that. ✨

**Comment by ElDeveloper** [comment]
> Would it be possible to update this so that blanks are associated with studies as well?

@tanaes, after going through the codebase to make these changes, I realized that the structure wasn't really meant for these changes (this took me a while). Therefore, I chatted about this with @josenavas and he clarified that blanks are not intended to belong to a single study, instead control samples are intended to belong to all studies included in a plate. When the sample information and prep information files are generated (at the end of the sequencing), the blanks are associated with the respective studies and they should be linked to the study at that stage. However, that last part is not implemented.

For now, I've decided to not commit any of the changes I had in place as they now seem very hacky and would circumvent the assumption above. If you think that's OK, then this PR should be ready 👍 

What do you think?

**Comment by tanaes** [comment]
Given the structure I guess that makes sense. It still poses a tactical
challenge later on as samples have to be unique in sample sheets. I’m
thinking now that this really militates for having a special “controls”
study to which these are all assigned.

**Comment by ElDeveloper** [comment]
I believe the sample names should be unique in the sample sheets and
across studies as they all are named according to four values:
"blank_type"."plate_id"."cell_row""cell_column".

**Comment by ElDeveloper** [comment]
Also, for posterity here's the diff of the patch I was working un before I talked to @josenavas. Note that some tests are failing:

<details>

git apply should do the trick:

```diff
diff --git a/labman/db/composition.py b/labman/db/composition.py
index 5d28c74..9ada939 100644
--- a/labman/db/composition.py
+++ b/labman/db/composition.py
@@ -552,14 +552,25 @@ class SampleComposition(Composition):
 
             return study
 
-    def update(self, content):
+    def update(self, content, study_id=None):
         """Updates the contents of the sample composition
 
         Parameters
         ----------
         content: str
             The new contents of the SampleComposition
+        study_id: str, optional
+            The study identifier to associate with this sample. Only to be
+            used with blank samples. It will be ignored otherwise.
         """
+
+        # remove the study id (if present in the sample name), we only need
+        # this to search over the composition types table
+        if study_id is not None and content.startswith(study_id):
+            blank_name = content.lstrip(study_id + '.')
+        else:
+            blank_name = content
+
         with sql_connection.TRN as TRN:
             # First check if the previous content matches the new one. If the
             # previous content is a experimental sample, then to be the same
@@ -568,13 +579,15 @@ class SampleComposition(Composition):
             sc_type = self.sample_composition_type
             contents_ok = True
             if not ((sc_type == 'experimental sample' and
-                     self.content == content) or (sc_type == content)):
+                     self.content == content) or (sc_type == content) or
+                    (study_id is not None)):
+
                 # The contents are different, we need to update
                 # Identify if the content is a control or experimental sample
                 sql = """SELECT sample_composition_type_id
                          FROM qiita.sample_composition_type
                          WHERE external_id = %s"""
-                TRN.add(sql, [content])
+                TRN.add(sql, [blank_name])
                 res = TRN.execute_fetchindex()
                 well = self.container
                 if res:
diff --git a/labman/db/process.py b/labman/db/process.py
index 0d15112..772b129 100644
--- a/labman/db/process.py
+++ b/labman/db/process.py
@@ -256,7 +256,7 @@ class SamplePlatingProcess(_Process):
             plate_id = TRN.execute_fetchlast()
         return plate_module.Plate(plate_id)
 
-    def update_well(self, row, col, content):
+    def update_well(self, row, col, content, study_id=None):
         """Updates the content of a well
 
         Parameters
@@ -267,13 +267,17 @@ class SamplePlatingProcess(_Process):
             The well column
         content: str
             The new contents of the well
+        study_id: str, optional
+            The study identifier that we want to associate this sample with.
+            Only used with blank samples, it will be ignored otherwise.
 
         Returns
         -------
         str
             The new contents of the well
         """
-        return self.plate.get_well(row, col).composition.update(content)
+        return self.plate.get_well(row, col).composition.update(content,
+                                                                study_id)
 
     def comment_well(self, row, col, comment):
         """Updates the comment of a well
diff --git a/labman/db/tests/test_composition.py b/labman/db/tests/test_composition.py
index 8a922b0..1477cc2 100644
--- a/labman/db/tests/test_composition.py
+++ b/labman/db/tests/test_composition.py
@@ -240,6 +240,46 @@ class TestsComposition(LabmanTestCase):
         self.assertIsNone(tester.sample_id)
         self.assertEqual(tester.content, 'blank.21.H1')
 
+    def test_sample_composition_with_study_id(self):
+        tester = SampleComposition(85)
+
+        # '1.blank', None -> bad
+        self.assertEqual(tester.update('1.blank'), ('1.blank', False))
+        self.assertEqual(tester.sample_composition_type, 'experimental sample')
+        self.assertIsNone(tester.sample_id)
+        self.assertEqual(tester.content, '1.blank')
+
+        # '1.blank', '1' -> good
+        self.assertEqual(tester.update('1.blank', '1'),
+                         ('1.blank.21.H1', True))
+        self.assertEqual(tester.sample_composition_type, 'experimental sample')
+        self.assertIsNone(tester.sample_id)
+        self.assertEqual(tester.content, '1.blank.21.H1')
+
+        # '1.blank', '' -> bad
+        self.assertEqual(tester.update('1.blank', ''), ('1.blank', False))
+        self.assertEqual(tester.sample_composition_type, 'experimental sample')
+        self.assertIsNone(tester.sample_id)
+        self.assertEqual(tester.content, '1.blank')
+
+        # 'blank', '' -> bad
+        self.assertEqual(tester.update('blank', ''), ('blank', False))
+        self.assertEqual(tester.sample_composition_type, 'experimental sample')
+        self.assertIsNone(tester.sample_id)
+        self.assertEqual(tester.content, 'blank')
+
+        # 'blank', '1' -> bad
+        self.assertEqual(tester.update('blank', '1'), ('1.blank', False))
+        self.assertEqual(tester.sample_composition_type, 'experimental sample')
+        self.assertIsNone(tester.sample_id)
+        self.assertEqual(tester.content, '1.blank')
+
+        # 'blank', None -> good
+        self.assertEqual(tester.update('blank', None), ('blank', False))
+        self.assertEqual(tester.sample_composition_type, 'experimental sample')
+        self.assertIsNone(tester.sample_id)
+        self.assertEqual(tester.content, 'blank.21.H1')
+
     def test_gDNA_composition_attributes(self):
         obs = GDNAComposition(1)
         self.assertEqual(obs.sample_composition, SampleComposition(1))
diff --git a/labman/gui/handlers/process_handlers/sample_plating_process.py b/labman/gui/handlers/process_handlers/sample_plating_process.py
index 39eabd0..3541ba4 100644
--- a/labman/gui/handlers/process_handlers/sample_plating_process.py
+++ b/labman/gui/handlers/process_handlers/sample_plating_process.py
@@ -66,16 +66,23 @@ def sample_plating_process_handler_patch_request(
             row = req_path[1]
             col = req_path[2]
             well_attribute = req_path[3]
+            study_id = None
+
             if well_attribute == 'sample':
                 if req_value is None or not req_value.strip():
                     raise HTTPError(
                         400, 'A new value for the well should be provided')
+
+                if '.' in req_value:
+                    study_id = req_value.split('.', 1)[0]
+
                 plates = Plate.search(samples=[req_value])
                 process = SamplePlatingProcess(process_id)
                 plates = set(plates) - {process.plate}
                 prev_plates = [{'plate_id': p.id, 'plate_name': p.external_id}
                                for p in plates]
-                content, sample_ok = process.update_well(row, col, req_value)
+                content, sample_ok = process.update_well(row, col, req_value,
+                                                         study_id)
                 return {'sample_id': content, 'previous_plates': prev_plates,
                         'sample_ok': sample_ok}
             elif well_attribute == 'notes':
diff --git a/labman/gui/static/js/plateViewer.js b/labman/gui/static/js/plateViewer.js
index 7eb8ba1..2eea4c6 100644
--- a/labman/gui/static/js/plateViewer.js
+++ b/labman/gui/static/js/plateViewer.js
@@ -251,6 +251,7 @@ PlateViewer.prototype.initialize = function (rows, cols) {
       // This is a new plate, we need to create the plate
       var plateName = $('#newNameInput').val().trim();
       var plateConf = $('#plate-conf-select option:selected').val();
+
       $.post('/process/sample_plating', {'plate_name': plateName, 'plate_configuration': plateConf}, function (data) {
         that.plateId = data['plate_id'];
         that.processId = data['process_id'];
@@ -367,6 +368,7 @@ PlateViewer.prototype.loadPlateLayout = function () {
  **/
 PlateViewer.prototype.modifyWell = function (row, col, content) {
   var that = this;
+
   $.ajax({url: '/process/sample_plating/' + this.processId,
          type: 'PATCH',
          data: {'op': 'replace', 'path': '/well/' + (row + 1) + '/' + (col + 1) + '/sample', 'value': content},
@@ -605,9 +607,9 @@ function SampleCellEditor(args) {
       // The user introduced an empty string. An empty string in a plate is a blank
       state = 'blank';
     }
-    if (!this.blankNames.includes(state)) {
+    // if (!this.blankNames.includes(state)) {
       // if the sample was neither an empty space NOR a known blank AND only
-      // study is selected in the UI, then prepend the study id to the name
+      // one study is selected in the UI, then prepend the study id to the name
       activeStudies = get_active_studies();
       if (activeStudies.length === 1) {
         studyPrefix = activeStudies[0] + '.';
@@ -615,7 +617,7 @@ function SampleCellEditor(args) {
         if (!state.startsWith(studyPrefix)) {
           state = studyPrefix + state;
         }
-      }
+      // }
     }
 
     // Replace all non-alpha numeric characters by '.'
```
</details>

**Comment by tanaes** [comment]
@ElDeveloper ok if i merge this?

**Comment by ElDeveloper** [comment]
🎉

**Pull request merged**
