### PR TITLE
Adding CHANGELOG.md

### PR DESCRIPTION
**Pull request by charles-cowart**
Adding CHANGELOG.md, based on feedback from team.

### CODE REVIEW

**Comment by charles-cowart** [comment]
@AmandaBirmingham Personally, I think everyone on the team should be able to edit the changelog when any change of significance has been made. It's probably a quicker way to get up to speed than going through the closed issues on GitHub.

**Comment by antgonza** [comment]
@AmandaBirmingham, good question! IMOO the highlights of the issues being solved or big decisions that might make an impact in the future.

For example, a release CHANGELOG could become [a user email of new features in the release](https://forum.qiime2.org/t/qiime-2-2019-1-release-is-now-live/8123) or a [simple summary of the big changes](https://github.com/biocore/qiita/blob/master/CHANGELOG.md).

**Comment by antgonza** [comment]
@charles-cowart, right but note that reviewers can also ask the PR author to add a line in the CHANGELOG; however, for Qiita I normally go over all the closed issued for that given release ...

**Comment by charles-cowart** [comment]
@antgonza seems like it's a matter of whether you want an continuously updated list, or a summary of changes compiled and published at release. I can go either way; I've done both.

**Comment by antgonza** [comment]
@charles-cowart, I _think_ we should start as a continuously updated list of good to knows, highlights of issues, etc until we have a formal release and then move to changes compiled and published at release but it's your call ...

**Comment by charles-cowart** [comment]
@antgonza Agreed! I was thinking the same thing, actually.

**Pull request merged**
