### PR TITLE
Add undo/redo functionality

### LINKED ISSUE #120: Implement "undo" functionality when plating samples

### PR DESCRIPTION
**Pull request by ElDeveloper**
Seems to be working now, except blank cells are saved with a blank placeholder i.e. if you paste 4 cells with no content, the grid will turn these into "blank entries". It's rather strange, before merging I recommend that you try this out locally. 

Fixes #120

### CODE REVIEW

**Comment by wasade** [comment]
@ElDeveloper merge conflicts now :/

**Comment by ElDeveloper** [comment]
Conflicts should be fixed now.

**Comment by josenavas** [comment]
@ElDeveloper does this work with any kind of edit or only when copy/pasting cells?

**Comment by ElDeveloper** [comment]
This should work with any kind of edit.

**Comment by josenavas** [comment]
Thanks!

**Pull request merged**
