### PR TITLE
All Python files have references to labman schema changed

### PR DESCRIPTION
**Pull request by charles-cowart**
All Python files have references to labman schema changed to
'labcontrol'. Consideration needs to be given to ensure existing
installations get their schemas renamed to 'labcontrol' before
unittests, etc. are run. Ensure 'labcontrol patch' is run at the right
time for new and existing users.

Test PR + run through Travis - confirm breakage due to populate being unchanged.

### CODE REVIEW

**Comment by charles-cowart** [comment]
This PR touches a lot of files, but for the most part, the changes are simple.

**Comment by wasade** [comment]
Seems fine

**Comment by charles-cowart** [comment]
> Seems fine

@wasade Want to officially approve it, and merge, then?

**Comment by charles-cowart** [comment]
Talked to @wasade. Going ahead with merging.

**Pull request merged**
