### PR TITLE
Sequence list

### PR DESCRIPTION
**Pull request by tanaes**
Fixes issue #96

### CODE REVIEW

**Comment by josenavas** [comment]
Sorry just noticed this. Can you change also the ones below? They're going to suffer from the same issue
```
$ grep -R "self.set_header('Content-Description', 'text/csv')" labman/
labman//gui/handlers/process_handlers/library_prep_shotgun_process.py:        self.set_header('Content-Description', 'text/csv')
labman//gui/handlers/process_handlers/normalization_process.py:        self.set_header('Content-Description', 'text/csv')
labman//gui/handlers/process_handlers/pooling_process.py:        self.set_header('Content-Description', 'text/csv')
```

**Comment by tanaes** [comment]
Done!

**Comment by josenavas** [comment]
Awesome thanks!

**Comment by ElDeveloper** [comment]
This looks good to me 👍

**Pull request merged**
