### PR TITLE
WIP: Gdna compression prepopulate

### PR DESCRIPTION
**Pull request by wasade**
Solves prepopulation for this page in #101 

I haven't been able to disable the "remove" buttons dynamically which is frustrating. I'm not sure what other things should be disabled when prepopulating so for right now I'm just disabling everything

### CODE REVIEW

**Comment by josenavas** [comment]
Thanks @wasade I'm going to pull down this into my local branch and I will investigate.

**Comment by josenavas** [comment]
I can't reproduce your issue, I think it must be some kind of race condition, which I can imagine where it is originating from. I, however, found a different issue that affects the structure on how we are storing the data of the compressed plates. I'm communicating with @AmandaBirmingham to see which is the best solution moving forward.

**Comment by wasade** [comment]
Okay thanks! I hope the issue isn't too deep

On Jan 24, 2018 2:54 PM, "Jose Navas" <notifications@github.com> wrote:

I can't reproduce your issue, I think it must be some kind of race
condition, which I can imagine where it is originating from. I, however,
found a different issue that affects the structure on how we are storing
the data of the compressed plates. I'm communicating with @AmandaBirmingham
<https://github.com/amandabirmingham> to see which is the best solution
moving forward.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jdereus/labman/pull/119#issuecomment-360301689>, or mute
the thread

**Comment by josenavas** [comment]
Closing in favor of #139

**Pull request closed without merging**
